# Generated by Django 5.1.2 on 2024-10-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=20)),
                ('no_wa', models.CharField(blank=True, max_length=20, null=True)),
                ('no_hp_suami', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat_ktp', models.TextField()),
                ('alamat_pengiriman', models.TextField()),
                ('link_maps', models.TextField(blank=True, null=True)),
                ('rekening_refund', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_inventory', models.CharField(max_length=50, unique=True)),
                ('merk', models.CharField(max_length=50)),
                ('tipe', models.CharField(max_length=50)),
                ('nomor_unit', models.IntegerField()),
                ('tanggal_pembelian', models.DateField()),
                ('posisi_saat_ini', models.CharField(default='Di Rak', max_length=100)),
                ('pemilik', models.ManyToManyField(related_name='inventory', to='inventory.pemilik')),
            ],
        ),
    ]
