# Generated by Django 5.1.2 on 2024-10-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_equipment_financialrecord_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='tracking',
        ),
    ]
