# Generated by Django 5.1.2 on 2024-10-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_ktp_address_customer_maps_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rental_history',
        ),
    ]
