# Generated by Django 5.1.2 on 2024-10-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='rental_price',
            new_name='monthly_rental_price',
        ),
    ]
