# Generated by Django 5.1.2 on 2024-10-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rental_end_date_rental_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rental_duration',
        ),
    ]
