# Generated by Django 5.1.2 on 2024-10-28 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_customer_rental_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='transfer_receipt',
            field=models.FileField(upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
