# Generated by Django 5.1.1 on 2024-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_transactions_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ktp_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_photos/'),
        ),
    ]
