# Generated by Django 5.1.1 on 2024-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_customer_ktp_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
