# Generated by Django 5.1.1 on 2024-11-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
